[project]
name = "diffusion-experiments"
version = "0.2.0"
description = "A collection of experiments with diffusion models."
requires-python = ">=3.12.0, <3.13"
dependencies = [
    "amici==0.34.2",
    "bayesflow==2.0.13",
    "benchmark-models-petab",
    "colorcet>=3.1.0",
    "fides==0.8.0",
    "fyeldgenerator>=0.1.7",
    "jax>=0.10.2 ; sys_platform != 'linux'",
    "jax[cuda13]>=0.10.2 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "joblib==1.5.2",
    "marimo>=0.19.6",
    "matplotlib>=3.10.8",
    "numpy>=2.3.5",
    "petab==0.7.0",
    "playwright>=1.57.0",
    "plotly>=6.5.2",
    "pyabc>=0.12.16",
    "pymc>=5.26.1",
    "pypesto==0.5.9",
    "sbibm",
    "tensorflow==2.20.0 ; sys_platform != 'linux'",
    "tensorflow[and-cuda]==2.20.0 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "torch>=2.5.1",
    "wandb>=0.27.0",
]

[tool.uv.sources]
benchmark-models-petab = { git = "https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab.git", subdirectory = "src/python", rev = "master" }
sbibm = { git = "https://github.com/arrjon/sbibm.git", rev = "dev" }
